version: 0.2

phases:
  runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - cd UI
      - yarn install  
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://gomart.shop