version: 0.2

env:
  variables:
    REPOSITORY_URI: public.ecr.aws/n1d3h0o8/gomart
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - git fetch --all
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n1d3h0o8

  build:
    commands:
      - if git diff --quiet HEAD $(git merge-base origin/master HEAD) -- api/item; then
        echo "No changes in api/item. Skipping Docker build.";
        else
        echo "Changes detected in api/item. Building Docker image...";
        docker build -t gomart/item:latest api/item ;
        docker tag gomart/item:latest $REPOSITORY_URI/item:latest ;
        docker push $REPOSITORY_URI:$IMAGE_TAG
        fi
