version: 0.2

phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - yarn install 
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://gomart.shop