version: 0.2

phases:
  pre_build:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - ls 
      - cd $CODEBUILD_SRC_DIR
      - cd UI
      - ls
      - yarn install  
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://gomart.shop