version: 0.2

phases:
  pre_build:
    commands:
      - npm install --prefix /codebuild/output/src517721435/package.json
      - npm install -g npm
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://gomart.shop