version: 0.2

env:
  variables:
    REPOSITORY_URI: public.ecr.aws/n1d3h0o8/gomart
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - git fetch --all
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n1d3h0o8

  build:
    commands:
      # Item Service
      - echo "Building api/item...";
      - docker build -f item.Dockerfile -t gomart/item:latest api/item ;
      - docker tag gomart/item:latest $REPOSITORY_URI/item:latest ;
      - docker push $REPOSITORY_URI:$IMAGE_TAG ;

      # Order Service
      - echo "Building api/order...";
      - docker build -f order.Dockerfile -t gomart/order:latest api/order ;
      - docker tag gomart/order:latest $REPOSITORY_URI/order:latest ;
      - docker push $REPOSITORY_URI:$IMAGE_TAG ;

      # Place Order Service
      - echo "Building api/place_order...";
      - docker build -f place_order.Dockerfile -t gomart/place_order:latest api/place_order ;
      - docker tag gomart/place_order:latest $REPOSITORY_URI/place_order:latest ;
      - docker push $REPOSITORY_URI:$IMAGE_TAG ;

      # stripe_wrapper Service
      - echo "Building api/stripe_wrapper...";
      - docker build -f stripe_wrapper.Dockerfile -t gomart/stripe_wrapper:latest api/stripe_wrapper ;
      - docker tag gomart/stripe_wrapper:latest $REPOSITORY_URI/stripe_wrapper:latest ;
      - docker push $REPOSITORY_URI:$IMAGE_TAG ;
